### ISSUE TITLE
investigate webrtc/RtcMultiConnection

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/EventManager#13]
investigate using instead of google hangouts api, which is being taken away.

https://github.com/muaz-khan/RTCMultiConnection

**Comment by arreche** [comment]
It would be a viable solution but we will have to build all the UI from scratch and deal with some quirks like...
* Hosting a [Signaling Server](https://github.com/muaz-khan/RTCMultiConnection/wiki/Custom-Private-Servers) (I got success deploying it in Drie and Heroku)
* [Echo cancelation](https://github.com/muaz-khan/RTCMultiConnection/wiki/How-to-fix-echo%3F)
* [Detect who is speaking](https://github.com/muaz-khan/RTCMultiConnection/wiki/Detect-Who-is-Speaking)
* [Recording sessions](https://github.com/muaz-khan/RecordRTC)

A simplified demo to perform an anonymous video conference and sharing screens can be found at https://github.com/arreche/conference

You can get more info about [RtcMultiConnection](https://github.com/muaz-khan/RTCMultiConnection) in the [wiki](https://github.com/muaz-khan/RTCMultiConnection/wiki)

**Comment by arreche** [comment]
@mattlindsey Could we close this now since you prefer to wait for any update from Google Hangout rather that implementing a custom video-conferencing service?

* https://youtu.be/7VcF98gydyU?t=281

**Comment by mattlindsey** [comment]
Closing, since a nice investigation into WebRTC was done.

Also, as Sam says, "for me EventManager is supposed to me agnostic as to whether it is working with hangouts, or Zoom, or a custom solution."
