### ISSUE TITLE
Filtering by user roles/permissions

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/EventManager#16]
This task should implement "Filtering by user roles/permissions"

**Comment by tansaku** [comment]
@mattlindsey out of interest - how does this relate to EventManager user stories?  I didn't realise we'd set up any roles/permissions stuff ...?

**Comment by tansaku** [comment]
ah I see you have 

```
 As an AV premium mob/F2F member
  So that I can see the next mob session of the week
  I'd like to see a list of archived and upcoming mob session
```

in the slack chat

I'd strongly recommend having those user stories in the tickets themselves - I think it's pretty dangerous to have a ticket called "Filtering by user roles/permissions" that has no connection to the motivation for the thing itself ...
