### ISSUE TITLE
api get list of events

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/EventManager#19]
Drive development using a test like this:

# spec/requests/api/v1/messages_spec.rb
describe "Messages API" do
  it 'sends a list of messages' do
    FactoryGirl.create_list(:message, 10)

    get '/api/v1/messages'

    json = JSON.parse(response.body)

    # test for the 200 status-code
    expect(response).to be_success

    # check to make sure the right amount of messages are returned
    expect(json['messages'].length).to eq(10)
  end
end

**Comment by tansaku** [comment]
@mattlindsey this functionality already provided by scaffolded code right?  

Also, as I mentioned last week - it would be really really could to have a link to (or the text of) the feature that this relates to

**Comment by mattlindsey** [comment]
Relates to:
Feature: Upcoming Event View
  As an AV member
  So that I can see if the next sessions fit my busy day
  I'd like to see the upcoming events of the day

**Comment by mattlindsey** [comment]
@tansaku This functionality (list of events) is not yet implemented.

**Comment by mattlindsey** [comment]
HOLD OFF ON THIS TICKET FOR NOW.
Pending some more research on what will be required by api client.
