### ISSUE TITLE
Add Ember frontend

### ISSUE THREAD

**Issue by mattlindsey** [AgileVentures/EventManager#29]
Move rails to 'backend' directory. Move cucumber up to top level 'features' directory.
Add starter EmberJS app in 'features' directory.

**Comment by mattlindsey** [comment]
See https://github.com/roschaefer/rundfunk-mitbestimmen for great example of this directory structure.

**Comment by mattlindsey** [comment]
@tansaku Now I'm worried about implementing the UI in the same repo as the API.
Are you OK with this?  It allows cucumber tests to sit on top of both of them and keeps them in sync easer.

**Comment by tansaku** [comment]
@mattlindsey it's okay for a spike, and it's okay in general - it's just important to be aware of the options.

You can have front end and back end in the same repo, or split them - there are pros and cons to each - think you could list what you think the pros and cons are?

**Comment by mattlindsey** [comment]
SAME REPO
PROS: Easier to acceptance test and maintain sync between UI and API
CONS: Hard to split into 3 repos, if that's desired to maintain 'separation'

DIFF REPOS
PROS: Maintains 'separation' of duties, tech stacks
CONS: Possibly requires 3 repos and api versioning, better stubbing

Any others?

**Comment by mattlindsey** [comment]
I said '3 repos' above, but would acceptance tests fit into both repos, making it only 2 required?

**Comment by tansaku** [comment]
my version ...

SAME REPO
PROS: 
 - Easier to acceptance test 
 - clear sync between UI and API

CONS: 
  - If we need to split into 3 repos later that is more work
  - anyone working on the app has to download all parts and have all parts running locally

DIFF REPOS
PROS: 
  - Maintains 'separation' of duties, tech stacks
CONS: 
 - Possibly requires 3 repos and api versioning, better stubbing
 - requires clearly maintained and versioned API
