### ISSUE TITLE
ensure that action cable works on some PaaS (heroku or drie etc.)

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/EventManager#6]

**Comment by arreche** [comment]
I confirm that It will works in Heroku

You can check it manually here
- https://agilevents.herokuapp.com/events

**Comment by tansaku** [comment]
great work @arreche - any wrinkles to what you needed to do during deploy?

**Comment by arreche** [comment]
Yes. There is a short tutorial in the Heroku's blog!
- https://blog.heroku.com/real_time_rails_implementing_websockets_in_rails_5_with_action_cable#deploying-our-application-to-heroku

**tl;dr**
- Replace default Rails database.
- Connect with a Redis server.
- Set up the right domain for action cable.

**Comment by mattlindsey** [comment]
Closing this.  Nice work @arreche.
